### ISSUE TITLE
Extra disk operations in a new OS

### ISSUE THREAD

**Issue by Pasha-From-Russia** [MiSTer-devel/Linux-Kernel_MiSTer#1]
Hello.

I moved from OS 210314 to the recent one (210825) and now I see Disk LED blinking even if the system is idle (1-4 blinks once in 4-7 seconds). Are there new apps added to OS that read/write the disk in the background? (I understand that there's a huge gap between 210314 and 210825)
Old system works fine...

**Comment by sorgelig** [comment]
it will be fixed soon. You can use kernel build from this issue:
https://github.com/MiSTer-devel/Main_MiSTer/issues/445#issuecomment-906432579

**Comment by movisman** [comment]
When creating a separate issue, I accidentally referenced this issue using the hash symbol and a number in the body of the text (I didn't realise it was shortcode for a reference), but I cannot remove the resulting above reference. This was not intended - apologies.

**Comment by sorgelig** [comment]
no problem

**Comment by sorgelig** [comment]
fixed
