### ISSUE TITLE
Wifi RTL8812BU does not work

### ISSUE THREAD

**Issue by sonik-br** [MiSTer-devel/Linux-Kernel_MiSTer#12]
I've got this Comfast CF-812AC (RTL8812BU) wifi dongle and it works fine under windows.
O mister it cant connect. Sometimes it lists the ssids, sometimes not. But even when it lists, I cant connect to the network.
Tested with latest update from today and with the previous one.
Adapter is listed on the [wiki](https://github.com/MiSTer-devel/Main_MiSTer/wiki/WiFi-setup#wifi-usb-dongles-confirmed-to-work-running-command-lsusb-on-linux-will-show-if-usb-id-matches) as working and it's on the [changelog](https://misterfpga.org/viewtopic.php?p=32159#p32159) since Aug 25.
Driver problem?

**Comment by sorgelig** [comment]
I don't know who listed this dongle as "tested". Probably you need to ask that person.
I don't have this dongle to test.
Issues may happen if 2.4GHz and 5GHz bands have the same SSID. In this case giving different SSID solves the issue.

**Comment by sonik-br** [comment]
Different SSIDs for my networks. A friend have one of the same model and it works.
There's anything I can do to debug it and try to fix?
I might have plugged it once in the mister before the support for it was added. Would it load and "cache" the wrong driver?

**Comment by sorgelig** [comment]
I'm not a driver developer, so i'm afraid debug data from driver won't help me.
Since it's working for your friend, then either:
1) try to plug it into other USB port and remove other USB devices while testing.
2) May be signal isn't strong enough for this module.

**Comment by sonik-br** [comment]
Tested without other devices connected.
Signal is good. Device is like 2 meters away from router with direct clean sight.

Also tested again with a clean install on another sd card. Same problem.
Log shows:

nl80211: kernel reports: Authentication algorithm number required

Leaving it here in hope of some help.

**Comment by sorgelig** [comment]
may be check encryption algo on router. 
Some routers has mixed authentication 802.11n/a/ac on 5GHz. If you have such option, then try 802.11ac only

**Comment by sonik-br** [comment]
I entered the router setup to look at those settings. They are correct.
But then I saw an fixed Channel Number at 11. Changed to Automatic and now it works!
Thanks for the help.

**Comment by sorgelig** [comment]
Especially 5GHz channels are starting from some ~50 numbers if i remember correct.
It's good you fixed the problem.
