### ISSUE TITLE
oled screen stops working after update / all linux.img kernel has one less file in a specific path 

### ISSUE THREAD

**Issue by pplatoon** [MiSTer-devel/Linux-Kernel_MiSTer#14]
hello I hope I can explain myself well. After doing update / all, the initial oled screen that put a different logo on each core has stopped working. I think it is because the kernel of linux.img has changed along with some things and in the path etc / init.d / the file s60i2c2oled related to boot is missing at the boot of the mister.
any ideas on this?

**Comment by sorgelig** [comment]
MiSTer has NO OLED screens. 
If you use 3rd party mods/addons then report it to corresponding manufacturer.

**Comment by pplatoon** [comment]
oh sorry I thought I could make the query close the post then and thanks for answering
