### ISSUE TITLE
8bitdo M30 Bluetooth controllers no longer work after 20200908 linux update

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Linux-Kernel_MiSTer#15]
See https://misterfpga.org/viewtopic.php?f=32&t=1165&p=10013#p10013

I can pair the controller fine, but the OSD refuses to recognize any buttons I press on it. I can’t even remap the buttons because when the remapping sequence asks me to press DPad-right, and I do, it acts as if I’m not.

Same problem with my other identical controller.

I think this is a Linux issue (rather than a Main/OSD issue) b/c I’m not seeing any js* devices appear in the filesystem anymore when I pair and connect any of my Bluetooth controllers.

**Comment by c0d3h4x0r** [comment]
FWIW, my Bluetooth keyboard still works fine; it’s only gamepads that are no longer working.

**Comment by c0d3h4x0r** [comment]
Everything was working fine after I last updated on Friday, but now it’s busted.  So it must be either the 20200907 main/OSD or the 20200908 linux that broke it.

**Comment by sorgelig** [comment]
try to roll back zImage_dtb file
May be it's related to Switch driver included in latest kernel

**Comment by sorgelig** [comment]
Try different M30 modes

**Comment by c0d3h4x0r** [comment]
Thanks, will try out those out. 

I already double-checked that my M30s are still set to Windows mode (w/ D-pad mapped to D-pad rather than left or right analog sticks).  Same as I’ve been using them for months.  Is it possible I may need to put them in a different mode now?

**Comment by sorgelig** [comment]
my M30 works fine in current build

**Comment by c0d3h4x0r** [comment]
Which M30 mode are you using?

**Comment by c0d3h4x0r** [comment]
Reverting to 20200618 zImage_dtb resolves it.  Switching back to 20200908 zImage_dtb breaks it again.

I downloaded a fresh copy of 20200908 zImage_dtb and compared md5 hashes to ensure I had a good copy of it (I did).

**Comment by sorgelig** [comment]
only Switch mode doesn't work. debug console outputs some exceptions. Probably Switch kernel driver has bug.
X-Input, D-Input and Apple modes are working.

**Comment by c0d3h4x0r** [comment]
I reset both M30 controllers and re-paired them using X-Input mode, and that resolved the problem.  Thanks!

**Comment by jloco** [comment]
I've successfully ran the update and my BT M30 has been working for me flawlessly in MacOS mode (START+A, and don't forget to press the sync button for 3 secs after).

**Comment by sorgelig** [comment]
i think it was some hiccup in setup as mine didn't stop working after update.
i close it.
