### ISSUE TITLE
ath9k_htc support

### ISSUE THREAD

**Issue by yanfali** [MiSTer-devel/Linux-Kernel_MiSTer#16]
Hi, would it be possible to add this USB wifi driver to that standard kernel modules? It's a stock driver and does work on rpi arm. Thanks

Yan

https://wiki.debian.org/ath9k_htc

**Comment by sorgelig** [comment]
Someone having such device may adopt it to MiSTer kernel.
But i suggest to buy already compatible WiFi dongle. It's hard to add side device driver without having a real HW. Also 802.11n today is already outdated version to care about it.

**Comment by yanfali** [comment]
Fair enough! I use a lot of 2.4 for iot and atheros is one of the better chips, but I will look into supported one.

**Comment by yanfali** [comment]
The sad part is almost none of the recommended dongles are available or use dodgy rtl parts.
