### ISSUE TITLE
Add Namco GunCon 2 driver

### ISSUE THREAD

**Issue by NolanNicholson** [MiSTer-devel/Linux-Kernel_MiSTer#17]
Hello,

This request pairs with https://github.com/MiSTer-devel/Main_MiSTer/pull/516 (just merged) to provide support in MiSTer for the Namco GunCon 2 lightgun.

Could you please include the GunCon 2 driver at https://github.com/beardypig/guncon2 in the kernel?

Sorry this isn't a PR; my only working copy uses an externally compiled module, since I'm not experienced at building new modules into the kernel itself.

Thank you!

**Comment by sorgelig** [comment]
I don't have this device, so i cannot test it. 
So it's better if you will try to merge it into Kernel source and make PR.
