### ISSUE TITLE
Default config results in a kernel where some peripherals don't work

### ISSUE THREAD

**Issue by NolanNicholson** [MiSTer-devel/Linux-Kernel_MiSTer#19]
If the kernel compilation instructions at https://github.com/MiSTer-devel/Main_MiSTer/wiki/Compiling-the-Linux-kernel-for-MiSTer are followed exactly on a clean Ubuntu installation, the resulting zImage_dtb file mostly works, but some peripherals no longer function. Examples of nonworking peripherals include CIFS mounts, the Edimax EW-7811Un, and the Xbox Elite Controller. However, most peripherals work fine.

This appears to be due to some discrepancies between the default settings in this repo (particularly Kconfig and Makefile?) and the settings used to compile release builds of the kernel:

- The build process needs to include the `EXTRAVERSION=-MiSTer` flag so that the resulting kernel name, 5.15.1-MiSTer, matches the name of the official release. Right now, the compiled kernel gets the version "5.15.1+".
- For the Edimax EW-7811Un wi-fi adapter to work, I had to flip CONFIG_RTL8188EU from "m" to "y". I'm not sure what the general solution for other wi-fi adapters here is; a quick try at flipping multiple wi-fi driver flags from "m" to "y" failed due to multiple conflicting definitions.

**Comment by sorgelig** [comment]
you can use `export LOCALVERSION=-MiSTer` before compiling for the same result.
No idea about EW-7811Un and CIFS.. Probably something wrong with modules compilation/adding to image.

**Comment by NolanNicholson** [comment]
We can add `export LOCALVERSION=-MiSTer` to the build guide - that is fine.

If you do find out which modules are compiled and added, and how that selection of modules differs from the default config, I'd be happy to get that into the guide as well. As I mentioned, I was able to get a _particular_ wi-fi driver working correctly, but not the same general coverage that the release builds have.

**Comment by sorgelig** [comment]
May be you can read more about compiling kernel with modules and how they are installed into system. It's general Kernel info, not MiSTer specific.

**Comment by NolanNicholson** [comment]
I'll educate myself a bit further and explore how I might compile it for more general wi-fi driver support. Thanks for your help!
