### ISSUE TITLE
jq now missing from linux image

### ISSUE THREAD

**Issue by flynnsbit** [MiSTer-devel/Linux-Kernel_MiSTer#20]
jq (https://stedolan.github.io/jq/) was included in the previous linux image prior to 3/15 update.  This tool is used to pull down update scripts from github.  Here is a reference command: https://raw.githubusercontent.com/flynnsbit/Top300_updates/main/_mister/update/AO486_Update_Top300_updater.sh

Line 66 is an example: 
`	read -r tag_name download_url < <(echo $(curl -k -s "${api_url}" | jq -r ".tag_name, .assets[0].browser_download_url"))`

**Comment by flynnsbit** [comment]
I'll do this another way.

**Comment by sorgelig** [comment]
Linux has been updated
