### ISSUE TITLE
Request: build Python with sqlite3 module

### ISSUE THREAD

**Issue by tonurics** [MiSTer-devel/Linux-Kernel_MiSTer#21]
Please include the sqlite3 module for Python.

It will allow us to create faster, safer, and more elegant solutions for working with persistent data.

Such is the case with update/downloader scripts. The current downloader script from theypsilon uses large JSON encoded files to store relational data. [I've also experimented with using the available dbm and CSV modules; but they introduce their own issues.]

Note: The sqlite3 module has been part of the Python standard library since 2.5. There are currently random Python files [cruft?] on the file system that expect it.

**Comment by theypsilon** [comment]
While the addition of sqlite3 would be welcomed, and that addition might be helpful for Downloader in the future, there is no real pressure to include it from Downloader side. For this tool there are many easier and more effective low hanging fruits to address before considering a change in the storage format, which most probably is not gonna bring much anyways.

That being said, sqlite3 could be helpful for other tools too, and will definitely be nice to have it available in the future, so to me it sounds that adding this package would be a good idea.

**Comment by birdybro** [comment]
+1 to this.

After a conversation with @tonurics I'm convinced that this would greatly improve the performance and the user experience when people are running Downloader, and has potential that could go beyond Downloader.

**Comment by ahmadexp** [comment]
/usr/lib which includes Python is part of loop8 which is only 375mb and is almost full. I am wondering if we can have a way to extend that partition in case someone likes to add more to python. I was able to install PIP3 but I cannot do anything further. I wanted to install (https://github.com/rm-hull/luma.oled) to add more advanced effect to the i2c2oled but I am stuck. It would be great if there was a way to expand "/"

**Comment by Koston-0xDEADBEEF** [comment]
As archive.org uses sqlite files to store metadata, having support for reading them would make it possible to write a much more sophisticated version of ROMweasel. It currently parses XML files, but those contain only a small fraction of data that's available in sqlite format.

Also like tonurics says, sqlite would be great for any other tool as well for working with persistent data.

**Comment by sajattack** [comment]
this isn't relevant to the kernel repo
