### ISSUE TITLE
Request: Mouse Wheel as Spinner for 2 mouse objects

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/Linux-Kernel_MiSTer#22]
Moved here from this request https://github.com/MiSTer-devel/NeoGeo_MiSTer/issues/161

https://www.amazon.co.jp/dp/B096FL5VXC/ - This is seen as a mouse device apparently, the trackball is the x and y for the mouse and the spinner is mouse wheel. vid:pid is 0ae4:0701 according to the user. Tested in the input core. Clockwise turn = increase mwhl number, counter-clockwise turn = decrease mwhl number.

https://www.amazon.com/gp/product/B002OOWB3O/ - This is a popular option for trackball users, seen as a mouse, trackball is x and y for the mouse, and the dial around the trackball is a mouse wheel. vid:pid is 047d:2048. When tested in the input core there is the same result as the first one, cw turn = increase and ccw turn = decrease. Below is the debug console output from this one:

clockwise
```
047d:2048:00 P0 Input event: type=EV_REL, Axis=8, Offset=-1
/dev/input/mouse0: dx=0, dy=0, scroll=1
PS2 MOUSE: 8 0 0 1
```
counter-clockwise
```
047d:2048:00 P0 Input event: type=EV_REL, Axis=8, Offset=1
/dev/input/mouse0: dx=0, dy=0, scroll=-1
PS2 MOUSE: 8 0 0 -1
```

**Comment by flynnsbit** [comment]
Verified, buttons map fine, the trackball is left/right on the mouse (already works in Arkanoid), spinner is the mouse scroll wheel and cannot be mapped or detected.

**Comment by super-triangle** [comment]
+1 to this request. I also have the Egret II spinner and I’d love to use it and the buttons on the device in MiSTer cores.

**Comment by CraftyDlx** [comment]
+1 also from me!

**Comment by wolfsoftgmbh** [comment]
+1 for me too. Its such a nice controller, hope somebody can do the driver part

**Comment by sorgelig** [comment]
too bad it doesn't include any dpad or joystick, so it cannot be used as standalone controller.

**Comment by birdybro** [comment]
That's true! One day someone will make the ultimate trackball+spinner arcade pad :P

**Comment by sorgelig** [comment]
while spinner is a good addition to controller, trackball/mouse is kind of redundant..
Another problem with this controller is inability to buy it.. If i would get this controller, then i would try to add reliable support for it.

**Comment by CraftyDlx** [comment]
> Another problem with this controller is inability to buy it.. If i would get this controller, then i would try to add reliable support for it.

It's not an issue at all to get it. This controller will shortly be available for the western market, see for instance
https://gamesrocket.com/eu/EGRET-mini-Paddle-and-Trackball-Game-Expansion-Set-Preorder/P27413-04
https://www.nin-nin-game.com/en/retro-games/49982-egret-2-mini-paddle-trackball-pack-taito-.html

Until then, it can be ordered as an import, e.g. from
https://www.amazon.co.jp/gp/product/B096FL5VXC/ (where I got mine)
https://www.japanzon.com/fr/taito-egret-ii-mini/17490-taito-egret-ii-mini-paddle-trackball-games-expansion-set--4988611221921.html
https://www.play-asia.com/paddle-trackball-games-expansion-set/13/70ema9

**Comment by birdybro** [comment]
This Arcade1Up Atari Couchcade might end up using it too, but this is more of an all-in-one system with games in it, so no word yet on if it can be used as a controller.

![image](https://user-images.githubusercontent.com/16388068/161264552-ee8d87d2-9187-485a-b518-aa07d028cd45.png)

A bit funky looking, but Arcade1Up sometimes makes good stuff. Just adding here for reference as later on it might be relevant and don't want to forget about it. Waiting on reviews to come out.

**Comment by CraftyDlx** [comment]
> Arcade1Up Atari Couchcade

Really? Looks awesome but the fact that's it's an all-in-one system and therefore the price of ~200$ will break it's neck. It contains only 10 dusty and rusty games you can play on MiSTer or any other emulator anyways and where is the SD-card slot for 200$? I might be a success as a plain stick but like that, no way.

**Comment by sorgelig** [comment]
> > Arcade1Up Atari Couchcade
> 
> Really? Looks awesome but the fact that's it's an all-in-one system and therefore the price of ~200$ will break it's neck. It contains only 10 dusty and rusty games you can play on MiSTer or any other emulator anyways and where is the SD-card slot for 200$? I might be a success as a plain stick but like that, no way.

lol.. looking at price of Egret 2 $263 the one above is a bargain 🤣 
Nope, guys... I don't play such games...

**Comment by CraftyDlx** [comment]
> looking at price of Egret 2 $263 the one above is a bargain

I think you misunderstood. This is not about the "Egret II Mini all in one system". This is about the "EGRET Ⅱ mini Paddle and Trackball Controller" which is separately available for about $95. There is no need to buy the "Egret II mini" for about $200 (see e.g. japanzon.com) if you only want the paddle controller.

Besides, comparing the "Egret II mini" with the "Arcade1Up Atari Couchcade" is to compare apples with oranges. The "Egret II mini" has an integrated, rotateable screen, 40 build-in games and a SD-card slot. But thats offtopic.

@birdybro You might like this: https://ultimatemister.com/product/ultimate-spinner-pro/

**Comment by birdybro** [comment]
I am aware of Ricardo's nice spinner. That spinner doesn't use a mouse wheel as the spinner though.

**Comment by MukiEX** [comment]
If anyone is looking for the input data on the Egret II Mini Trackball (Model No: TAS-P-001)

(all this via an ubuntu box; there's no evtest in MiSTer afaik)

From `lsusb`:

```
0ae4:0701 Taito Corp.
```

From `evtest`:

Left 30mm button (EV_KEY (value 0 off, value 1 on)):
```
(EV_MSC), code 4 (MSC_SCAN), value 9001d
(EV_KEY), code 300 (?), value 0
```

Right 30mm button:
```
(EV_MSC), code 4 (MSC_SCAN), value 9001e
(EV_KEY), code 301 (?), value 0
```

Upper-Left 15mm button (purple):

```
(EV_MSC), code 4 (MSC_SCAN), value 90017
(EV_KEY), code 294 (BTN_BASE), value 0
```

Upper-Right 15mm button (blue):
```
(EV_MSC), code 4 (MSC_SCAN), value 90018
(EV_KEY), code 295 (BTN_BASE2), value 0
```

Center-Bottom 15mm button (white):
```
(EV_MSC), code 4 (MSC_SCAN), value 9001a
(EV_KEY), code 297 (BTN_BASE4), value 0
```

Turning the wheel (Positive values going clockwise, Negative values going counter clockwise, lowest/highest values I saw were 50/-71, though I'd imagine I didn't spin it as fast in one direction, they both probably top off equally):
```
(EV_REL), code 8 (REL_WHEEL), value -1
```

Trackball (tops out at less than -19/19 in any direction being spun FAST.):

Up is negative REL_Y, Down is positive REL_Y
Left is negative REL_X, Right is positive REL_X

```
(EV_REL), code 0 (REL_X), value -1
(EV_REL), code 1 (REL_Y), value 1
```

In Windows the trackball moves relatively slowly and the spinner/scroll wheel moves pretty quickly. I have to "swipe" the rolling ball a good ten times to get from one end of the screen to the other (no acceleration curve detected in Windows). But the scroll wheel can get to the top or bottom of this Github page with a few mm of travel. Not sure if this is at all helpful; if need be I'll be happy to record more data.

**Comment by gus0650** [comment]
+1 from me

**Comment by poopybunghole** [comment]
Might even be fun just to play these games with a mouse scroll wheel even if you don't have a spinner.  As it is currently an unused input method.  Also a potential cheap method of DIY spinners.  Worth adding the functionality I think.

**Comment by theypsilon** [comment]
I managed to make it work, I'll try to prepare a PR when I have time

**Comment by super-triangle** [comment]
@theypsilon That's awesome to hear! Looking forward to playing Arkanoid with it. :D

**Comment by flottenheimer** [comment]
+1
What is the status on this?
I just received my Taito egret II Mini Spinner/Trackball-controller last week and would loooove for it to work with Arkanoid and Breakout on the amazing MiSTer. Not at least for when Revenge of DOH is ready. 🔥

**Comment by denisbr** [comment]
> I managed to make it work, I'll try to prepare a PR when I have time

How is it going with the PR?

**Comment by gingerbeardman** [comment]
Following.

**Comment by denisbr** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/compare/master...theypsilon:Main_MiSTer:test-unstable-taito-spinner-firmware#diff-15bfc15588deaba1e467e30182d44d269884d911e5d684edacab95d8cffe7ba0

This is the relevant diff.
@theypsilon, can I ask whether this is a working solution or if it would require a lot more work to be production ready?

**Comment by retrob0t** [comment]
Mouse wheel as spinner has been implemented in MiSTer main, and is working correctly for the Egret II mini spinner/trackball controller.

This issue can be closed.
