### ISSUE TITLE
Missing module for ch34x devices

### ISSUE THREAD

**Issue by ojaksch** [MiSTer-devel/Linux-Kernel_MiSTer#22]
We are creating non commercial ESP32 based display modules for the MiSTer, which are displaying what core is starting (see https://misterfpga.org/viewtopic.php?f=9&t=1887). Some of these devices are providing a ch34x converter for the commuication between USB and the ESP32 device, which the Linux kernel for MiSTER is lacking of.
Would you mind to include this module in future version of MiSTER's Linux kernel?

**Comment by sorgelig** [comment]
Should be no problem to add it if it's available in current Kernel version.

**Comment by ojaksch** [comment]
That would be fantastic! Meanwhile I've build my own kernel according to https://github.com/MiSTer-devel/Main_MiSTer/wiki/Compiling-the-Linux-kernel-for-MiSTer, enabled CONFIG_USB_SERIAL_CH341=y there and it's working great now.

![IMG_20210420_055731](https://user-images.githubusercontent.com/17717333/115335852-518c8380-a19e-11eb-9fb8-b2dea9962c01.jpg)

**Comment by sorgelig** [comment]
ok

**Comment by ojaksch** [comment]
...integrated in Kernel now. Thanks a lot!
