### ISSUE TITLE
Request: enable rumble on Pantherlord USB to PS1 controller adapter

### ISSUE THREAD

**Issue by fjmartinez2k** [MiSTer-devel/Linux-Kernel_MiSTer#26]
Hi,

If possible, please add `CONFIG_PANTHERLORD_FF=y` to kernel config file to enable rumble on Pantherlord USB to PS1 Dual adapter.

Best regards,

**Comment by sorgelig** [comment]
if you already know how to make it, then better make a pull request with required change

**Comment by fjmartinez2k** [comment]
Created pull request as requested
