### ISSUE TITLE
Sony DualSense (Wired) doesn't connect on official usb hub, but works on makerspot otg usb hub

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/Linux-Kernel_MiSTer#28]
Here's the log on my Makerspot OTG USB Hub, the Sony DualSense (DualShock 5) connected via USB-C.

[log.txt](https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/files/8683200/log.txt)

When I attempt to connect it on the other MiSTer I have which has a USB Hub 2.1 from misteraddons, here is the log:

[log2.1.txt](https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/files/8683230/log2.1.txt)

Another user experienced the same kind of thing with their usb hub 2.1 in the discord, so I looked into it, and here are the results.

**Comment by sorgelig** [comment]
for me it works fine with official usb hub.
It's just known generic problem of DE10-nano USB host. Try other port on hub, try to remove or change ports of other connected USB devices, etc..

**Comment by birdybro** [comment]
Actually, this gets resolved immediately after running the firmware updater for the dualsense, located here --> https://controller.dl.playstation.net/controller/lang/en/fwupdater.html
