### ISSUE TITLE
How to know if a wheel device is supported?

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/Linux-Kernel_MiSTer#37]
![image](https://user-images.githubusercontent.com/447481/209784239-b48e43ec-ac24-42a9-a767-4de2e01d659f.png)
See bottom of the screen.

Looks like my old "Guillemot Thrustmaster force feedback racing wheel" is getting detected by linux drivers. But I don't know how to later configure in PSX to make it work.

Is there any utility in the linux side to make sure it is getting well detected?

**Comment by jsmolina** [comment]
@atrac17 did I miss something there?
Lot of thanks

**Comment by dnwe** [comment]
@jsmolina see https://github.com/MiSTer-devel/Main_MiSTer/issues/799

**Comment by jsmolina** [comment]
> @jsmolina see [MiSTer-devel/Main_MiSTer#799](https://github.com/MiSTer-devel/Main_MiSTer/issues/799)

wow! thank you so much!!!
It is a nice wheel and unsupported currently on actual windows versions (well, there are unofficial drivers but I was unable to install them)
