### ISSUE TITLE
wifi Realtek 8821AU/8812AU/8821CU broken drivers please sync with upstream

### ISSUE THREAD

**Issue by ghost** [MiSTer-devel/Linux-Kernel_MiSTer#39]
as per https://misterfpga.org/viewtopic.php?t=407&start=30
8821au based dongles seems to have trouble with associate even with open network
there is a better than upstream , maintainted by aircrack-ng project , driver for realtek 8821au/8812au/8821cu cards

https://github.com/morrownr/8821au-20210708
https://github.com/morrownr/8821cu-20210118
https://github.com/morrownr/8812au-20210629

which being updated and maintained by aircrack-ng community

**Comment by gkrzystek** [comment]
for thsoe who don't have skills to compile 
[88XXau.ko.zip](https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/files/10608915/88XXau.ko.zip)
unzip file
put 88XXau.ko.xz  to /lib/modules/5.15.1-MiSTer/kernel/drivers/net/wireless/
create file if not exists
/media/fat/linux/u-boot.txt
with content
v=loglevel=4 usbhid.jspoll=1 xpad.cpoll=1 modprobe.blacklist=8812au
reboot

**Comment by ghost** [comment]
[RTL-MiSTer-patch.zip](https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/files/10609853/RTL-MiSTer-patch.zip)

for those who don't have time to compile kernel, binary modules with installer/deinstaller
simply put whole RTL folder to root of your SD card.
boot mister, switch to test console, or ssh (over ethernet)
then execute /media/fat/RTL/install.sh

script will backup original driver, install new, reboot
test if it helps with your realtek based dongle.
report success , or failure

have fun

NineX

**Comment by sorgelig** [comment]
It would be good if you would make PR for kernel

**Comment by sorgelig** [comment]
ah, ok.
