### ISSUE TITLE
LFTP disappeared with Linux Update v210829

### ISSUE THREAD

**Issue by Polo2018** [MiSTer-devel/Linux-Kernel_MiSTer#5]
Hi, 

At first, thank you very much for your incredible and hard work.

It's a pity that you removed LFTP from the Linux Update v210829. It's very useful for me.

Best regards.

**Comment by sorgelig** [comment]
why don't use curl or wget?

**Comment by Polo2018** [comment]
I use special sync options that don't exist in curl or wget.

**Comment by kaloun34** [comment]
Hello

LFTP has  built-in mirror commands

**Comment by sorgelig** [comment]
ok, i will remove ncftp and add lftp

**Comment by kaloun34** [comment]
A very big thank you !!

**Comment by Polo2018** [comment]
Thank you very much Sorgelig!

Best regards.

**Comment by sorgelig** [comment]
done
