### ISSUE TITLE
Request: assign rmem_max 

### ISSUE THREAD

**Issue by psakhis** [MiSTer-devel/Linux-Kernel_MiSTer#51]
Hi,
I can't resolve that rmem_max is assigned to 2097152 for MiSTer at boot. I need that because i have received buffer errors without it.

1) Tried SO_RCVBUFFORCE inside MiSTer main
2) Tried user-start.sh with "sysctl -w net.core.rmem_max 2097152" or "sysctl -p" with /etc/sysctl.conf

If i kill MiSTer main and re-run, rmem_max is working properly. It's possible to do that by default on kernel?

Thank you

**Comment by sorgelig** [comment]
You may propose pull request.

**Comment by psakhis** [comment]
Seems not needed if i don't fragment udp packets. Can be close this request.

Thanks!
